name: sync content

# on: [push]

jobs:
  sync:
    name: sync content
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ .secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
      
      - name: sync master branch
        if: github.ref == 'refs/head/master'
        uses: ./.github/actions/s3-sync
        with:
          source: .
          destination: 